nwithan8/tauticord

- Tauticord.py
- requirements.txt
added enhancments from #2 and #3 + a few others
> some enhancments

- modules/config_parser.py
> Fix config parsing of non-existent config file (i.e. Docker environment)

- .github/workflows/docker.yml
- README.md
> Push Docker image to GitHub Packages as well as DockerHub

- Dockerfile
- README.md
- Tauticord.py
- ecosystem.config.json
- modules/discord_connector.py
- pm2_keepalive.py
> Restart bot (via Docker) if script exits

- modules/config_parser.py
- modules/discord_connector.py
- modules/tautulli_connector.py
- run.py
If none of the voice channel settings are enabled, don't bother making the voice category
Closes #66
> Avoid empty voice categories

- modules/discord_connector.py
Previously, when the bot looks for the proper voice channel to edit stats for, it was not considering category. If running multiple instances of Tauticord, this could mean the bot was accidentally selecting the wrong voice channel to edit. Now, channel location is limited to a specific category. If two instances are running, and categories are different names (e.g. `Server1` and `Server2`), it should now respect those categories when updating voice channels.
Closes #81
> Limit voice channel edits to specific category

- modules/tautulli_connector.py
```
📄 Plex Web (My Player Name)
```
```
📄 Plex Web (Anonymous)
```
> Make player anonymous if Anonymous Users enabled

- .github/workflows/on_commit.yml
- ci/env_vars_check.py
- modules/config_parser.py
- Remove unused env vars from config_parser.py
> New CI check to ensure environmental variables are documented

- requirements.txt
> Add missing psutil dependency

- modules/discord_connector.py
> Create channel under category

- modules/text_manager.py
> [bug] Fix circular import for type hint

- modules/config_parser.py
- modules/statics.py
- modules/tautulli_connector.py
- modules/text_manager.py
- modules/time_manager.py
- modules/utils.py
- run.py
- Add updated timestamp to summary message
- Replace internal time settings with time manager for easier and consistent time formatting
> [feat] Add "Updated" timestamp to summary message to show last time message was posted

- modules/config_parser.py
- modules/utils.py
> [chore] Format text channel name behind-the-scenes to account for Discord formatting rules

- modules/discord_connector.py
Fix misconfiguration that was causing bot to not use channel IDs properly when updating stats voice channels
> [fix] Fix using channel IDs when updating stats voice channels

- modules/tautulli_connector.py
- requirements.txt
Will make errors more obvious if related to Tautulli versus something else
> [chore] Bump dependencies

- modules/statics.py
> - Fix git version fallback if git repo not found

- modules/discord_connector.py
> [fix] Remove accidental emoji parameter

- modules/discord/discord_connector.py
- modules/versioning.py
- run.py
> [FIX] Version checking async loop blocking bot from starting

- ecosystem.config.json
- modules/errors.py
Mitigate issues like #165 due to new privilege requirements in v4.0.0+
> [fix] Kill app if missing privileged intents to avoid resetting tokens

- legacy/config_parser_v1.py
- migrations/migration_manager.py
> [FIX] Verify migration folders exist before running migrations
