README.md, Tauticord.py, config.py.sample, modules/discord_connector.py, modules/logs.py, modules/tautulli_connector.py, modules/vars.py
As it says in my modified readme:
MODIIFIED FROM nwithan8's version in the following ways:
- Faster and more efficient thanks to minimal communication with Discord
- Edit a single message with updated information rather than delete and replace (but replace if message isn't the bottom-most message in the channel)
- Only edit/add message if message contents differ from previous message, so almost all communication with Discord is eliminated
- Add/remove individual reactions only when neessary
- Use of embeds (optional) and more symbols for more aesthetic output
- Use convenient units for bitrate reporting
- Include media type in stream info
=> Minimize communication with Discord for performance and aesthetic gain, and pretty things up with embeds (optional) and more symbols

modules/discord_connector.py
Fixes py-cord get_guild() call to use positional args instead of keyword args.
py-cord's get_guild() function's id arg is purely positional, and would throw this error when voice channels were enabled:
> TypeError: Client.get_guild() got some positional-only arguments passed as keyword arguments: 'id'
This PR fixes the issue, and by extension fixes voice channel support.
=> fix: Fixes py-cord positional args

README.md
=> Add Docker environmental variables to README.md

modules/tautulli_connector.py
Common issue users face:
```
2023-04-21 03:17:24,669 - [INFO]: Starting Tauticord...
2023-04-21 03:17:24,669 - [CRITICAL]: Fatal error occurred. Shutting down: 'NoneType' object has no attribute 'endswith'
```
Due to `base_url` being empty (not parsed correctly). Redirect error to a more human-understandable error message.
=> Catch common configuration error, make more readable exception

modules/discord_connector.py, modules/utils.py
- Memory performance voice channel now displays percentage as well as usage
- **BREAKING**: `Remote Bandwidth` and `Local Bandwidth` channels renamed `Remote BW` and `Local BW` respectively to save space.
- Will cause the channels to be remade, users will have to delete the old channels
- Percentages now displayed with 1 decimal place rather than 2 to save space.
=> [feat] Add memory percentage

modules/config_parser.py, modules/time_manager.py
Bot will now print the parsed configuration into the debug logs at boot time. This is NOT the config file or environmental variables, but rather what the bot was able to parse (what actual settings it's operating with).
=> [chore] Print parsed configuration into logs

modules/discord_connector.py, modules/emojis.py, modules/tautulli_connector.py, run.py
Bot was not considering the custom styled numerical emojis when determining stream number.
Closes #123
=> [fix] Fix stream number emoji determination when using custom emojis

modules/emojis.py
Move from index calculation to key-value pair comparison. Casting a string to an integer is janky, but only just as janky as determining the index + 1
Closes #123
=> [fix] Fix stream number emoji determination when using custom emojis (again)

modules/logs.py, run.py
Seeing as I ran out of space on my VPS today because Tauticord's logs had reached 2.9 GB, this is long overdue.
Max log file size is 5 MB (should be good for several iterations), with 5 additional rolling logs, for a total of 6 * 5 = 30 MB of logs maximum.
Closes #139
=> [chore] Add 5 MB log rotation + 5 backups

modules/logs.py
Console and file logs now respect the user-configured timezone
**NOTE**: Due to chicken-egg problem, timezone CANNOT be read from the config file, only from an environmental variable. Timezone will only be applied is users use env vars to configure their container rather than config file.
Closes #141
=> [feat] Logs use configured timezone

.gitignore, Dockerfile, ecosystem.config.json, modules/errors.py, run.py
- Improve base image used for Docker container (lock to Python 3.10)
- Install latest PM2 in container (previous base image was 2+ years out of date and missing features)
- Remove unused pm2-logrotate
- Improve PM2 process
- Name `tauticord` process properly
- Auto-restart the bot if the config file changes
- Cancel auto-restart based on process exit status code
- Parse bot-killing exception to determine proper exit code
- Throw code 101 (avoid constant restart) if exception due to invalid Discord token
=> [feat] Improve Docker base, PM2, auto-restart settings

ecosystem.config.json
Ignore logs in PM2 watcha strategy, in case users accidentally put the logs directory in the config directory.
=> [fix] Ignore logs for PM2 restart strategy

ecosystem.config.json
Some users seem to use the same mapped folder for both logs and config files, making "watch the `/config` folder for changes" the same as "watch the `/log` folder for changes", causing every log event to endlessly reboot the bot.
Rather than explicitly ignoring every single possible log file (the regex patterns promised by the PM2 documentation don't actually work, looking at the source code), we'll only specifically watch for changes to the `/config/config.yaml` file.
=> [chore] Only auto-restart bot if specifically the config file has changed

modules/discord/command_manager.py, modules/discord/discord_connector.py, modules/settings/config_parser.py
- Fix Tautulli User Count channel not being updated, due to issue with parsing setting (closes #170)
- Fix slash commands not being enabled/disabled according to setting, due to missing sync
=> [Fix] User count display, slash commands setting

ecosystem.config.json, migrations/001_env_var_to_config_yaml.py, migrations/001_env_var_to_config_yaml.sh, migrations/base.py, modules/settings/config_parser.py, modules/settings/config_writer.py, modules/text_manager.py
- Bash + Python scripts to create `migrated_config.yaml` from environmental variables
- Run migration script as part of PM2 (one-time)
Part of [move away from environmental variables](https://github.com/nwithan8/tauticord/blob/135b3157e906031946a7a73f5345aa3dd0bade8a/documentation/ANNOUNCEMENTS.md#dropping-environmental-variable-support).
=> [chore] New migration script to generate config.yaml file from environmental variables

.schema/config_v2.schema.json, documentation/DOCUMENTATION.md, migrations/m002_old_config_to_new_config.py, modules/settings/config_parser.py, tauticord.yaml.example
User can override the default channel name for any voice channel (not recommended for library stat channels)
=> [feat] Add ability to override name for any voice channel

modules/discord/command_manager.py, modules/discord/discord_connector.py, modules/discord/discord_utils.py
- Remove default channel type for Discord causing creation errors in switch-case (closes #201 )
- Improve logs for slash command syncing
=> [fix] Channel type default causing Discord channels to not be created

.dockerignore, .schema/config_v2.schema.json, Makefile, migrations/m002_old_config_to_new_config.py, modules/discord/discord_connector.py, modules/discord/discord_utils.py, modules/settings/config_parser.py, modules/settings/models/__init__.py, modules/settings/models/discord.py, modules/tasks/activity.py, modules/versioning.py
- Can customize bot's Discord activity status, or use default "Watching Tautulli stats" status (closes #203 )
- Option to display live stream count in activity status, or fallback to GitHub link
- Minor verbiage improvements
=> [feat] Option to customize bot's Discord activity status

modules/discord/discord_utils.py
Discord really discourages users from using custom messages by making their parameters behave differently server-side for custom messages versus standard activity 😞
=> [fix] Custom status not being displayed

modules/discord/services/base_service.py, modules/discord/services/live_activity.py, modules/errors.py
Boolean deciding if live activity service (summary message + voice channel stats) should run was only considering if voice channel stats was enabled.
=> [fix] Live activity service message not updating if voice channel stats disabled

modules/discord/services/live_activity.py, modules/tasks/voice_category_stats.py
If voice channel stats are disabled, voice category was not collected, meaning regardless of whether text summary message was enabled/disabled, cron job to update live data was not running.
=> [fix] Override voice channel check when determining if live activity cron should start

modules/emojis.py, modules/statics.py, modules/tasks/activity.py, requirements.txt
The previous emojis past 9 were invalid, and could (should) not be used as reactions in Discord.
Instead, past the first 10 streams (1-9 + 0), colored square + colored circle emojis will be used to denote each stream and display the termination reaction.
Termination reaction count has also been reduced from 36 to 20, as 20 is the maximum number of reactions any one user can make on any given Discord message. Embed still has support for displaying up to 28 streams. If you have more than 28 concurrent streams... good for you.
=> [fix] Emojis (reactions) not being displaying

.schema/config_v2.schema.json, documentation/ANNOUNCEMENTS.md, migrations/m002_old_config_to_new_config.py, modules/discord/commands/summary.py, modules/discord/models/tautulli_activity_summary.py, modules/discord/services/live_activity.py, modules/settings/config_parser.py, modules/settings/models/discord.py, modules/tasks/activity.py, modules/tautulli/tautulli_connector.py, modules/text_manager.py, tauticord.yaml.example
Users can now disable the termination reaction emojis independently of whether they have a Plex Pass. Setting will do nothing if user ultimately does not have a Plex Pass
Closes #216
=> [feat] Add option to disable termination reaction options

modules/settings/config_parser.py, modules/utils.py, run.py
- Log pre-parsing config (the data extracted from the config YAML file)
- Log post-parsing config (the in-memory settings the bot will use)
- Exit bot without restart if Pydantic validation error during config parsing
=> [chore] Improve config parsing

documentation/ANNOUNCEMENTS.md, documentation/DOCUMENTATION.md, requirements.txt
Bump `tautulli` dependency, which drops Tautulli v2.13 and v2.14 support due to breaking API changes.
=> [chore] Add Tautulli v2.14 compatibility, drop v2.12 and v2.13 support
